// Preset expertise categories & skills shown in EditSkillsDialog.
// Designed to cover many professions, not just IT.

export interface SkillPresetCategory {
  category: string;
  description: string;
  skills: string[];
}

export const SKILL_PRESETS: SkillPresetCategory[] = [
  {
    category: "Design & Creative",
    description: "Visual design, branding, and creative production.",
    skills: [
      "Graphic Design",
      "UI Design",
      "UX Design",
      "Branding",
      "Illustration",
      "Logo Design",
      "Typography",
      "Figma",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Canva",
    ],
  },
  {
    category: "Photography & Video",
    description: "Capturing and producing visual stories.",
    skills: [
      "Portrait Photography",
      "Wedding Photography",
      "Product Photography",
      "Photo Editing",
      "Lightroom",
      "Videography",
      "Video Editing",
      "Color Grading",
      "Motion Graphics",
      "Adobe Premiere",
      "DaVinci Resolve",
    ],
  },
  {
    category: "Writing & Content",
    description: "Words, stories, and content that connect with people.",
    skills: [
      "Copywriting",
      "Content Writing",
      "Blogging",
      "Editing",
      "Proofreading",
      "Translation",
      "Storytelling",
      "Technical Writing",
      "Scriptwriting",
      "SEO Writing",
    ],
  },
  {
    category: "Marketing",
    description: "Promoting brands and growing audiences.",
    skills: [
      "Digital Marketing",
      "Social Media",
      "SEO",
      "SEM / Google Ads",
      "Email Marketing",
      "Content Strategy",
      "Influencer Marketing",
      "Branding",
      "Market Research",
      "Analytics",
    ],
  },
  {
    category: "Business & Management",
    description: "Leading teams, planning, and growing organizations.",
    skills: [
      "Project Management",
      "Product Management",
      "Operations",
      "Leadership",
      "Strategy",
      "Negotiation",
      "Public Speaking",
      "Agile / Scrum",
      "Consulting",
      "Entrepreneurship",
    ],
  },
  {
    category: "Finance & Accounting",
    description: "Numbers, planning, and financial decisions.",
    skills: [
      "Accounting",
      "Bookkeeping",
      "Financial Analysis",
      "Auditing",
      "Tax",
      "Budgeting",
      "Investment Analysis",
      "Excel",
      "QuickBooks",
    ],
  },
  {
    category: "Sales & Customer Service",
    description: "Building relationships and supporting customers.",
    skills: [
      "B2B Sales",
      "Retail Sales",
      "Customer Support",
      "CRM",
      "Lead Generation",
      "Account Management",
      "Cold Calling",
      "Negotiation",
    ],
  },
  {
    category: "Education & Training",
    description: "Teaching, mentoring, and developing others.",
    skills: [
      "Teaching",
      "Tutoring",
      "Curriculum Design",
      "Public Speaking",
      "Mentoring",
      "Coaching",
      "E-Learning",
      "Workshop Facilitation",
    ],
  },
  {
    category: "Healthcare",
    description: "Caring for people's health and wellbeing.",
    skills: [
      "Nursing",
      "Patient Care",
      "First Aid",
      "Medical Records",
      "Pharmacy",
      "Physiotherapy",
      "Nutrition",
      "Mental Health Support",
    ],
  },
  {
    category: "Engineering & Trades",
    description: "Hands-on technical and engineering crafts.",
    skills: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Civil Engineering",
      "Welding",
      "Carpentry",
      "Plumbing",
      "Automotive Repair",
      "CAD / AutoCAD",
      "SolidWorks",
    ],
  },
  {
    category: "Hospitality & Culinary",
    description: "Food, service, and guest experiences.",
    skills: [
      "Cooking",
      "Baking",
      "Pastry",
      "Barista",
      "Bartending",
      "Hotel Management",
      "Event Planning",
      "Customer Hospitality",
    ],
  },
  {
    category: "Music & Performing Arts",
    description: "Performance, composition, and stagecraft.",
    skills: [
      "Singing",
      "Songwriting",
      "Music Production",
      "Guitar",
      "Piano",
      "DJing",
      "Acting",
      "Dancing",
      "Theatre",
    ],
  },
  {
    category: "Web & Software Development",
    description: "Building websites, apps, and digital products.",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Vue",
      "Tailwind CSS",
      "Node.js",
      "Laravel",
      "React Native",
      "Flutter",
      "Python",
      "Java",
      "C++",
    ],
  },
  {
    category: "Data & AI",
    description: "Turning data into insights and intelligent systems.",
    skills: [
      "Data Analysis",
      "Data Visualization",
      "SQL",
      "Excel",
      "Power BI",
      "Tableau",
      "Machine Learning",
      "Python",
      "Pandas",
      "TensorFlow",
    ],
  },
  {
    category: "Languages",
    description: "Languages you speak or write fluently.",
    skills: [
      "English",
      "Indonesian",
      "Mandarin",
      "Japanese",
      "Korean",
      "Arabic",
      "Spanish",
      "French",
      "German",
    ],
  },
];
